In [78]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.datasets import  load_iris

In [79]:
# ANS 1:
df = load_iris()

In [80]:
df.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [81]:
x = df.data
y = df.target

In [82]:
from sklearn.model_selection import train_test_split
x_train ,x_test,y_train,y_test =train_test_split(x,y,test_size=0.25,random_state=10)

In [83]:
from sklearn.neighbors import KNeighborsClassifier

In [84]:
classifier = KNeighborsClassifier(n_neighbors=3)

In [85]:
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [86]:
y_pred = classifier.predict(x_test)

In [87]:
from sklearn.metrics import accuracy_score

In [88]:
print(accuracy_score(y_test,y_pred))

0.9736842105263158


In [89]:
# ANS 2 
df2 = pd.read_csv("BostonHousing.csv")

In [90]:
df2.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [91]:
df2.isnull().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [92]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64  
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64  
 9   tax      506 non-null    int64  
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [93]:
x1 = df2.iloc[:,:]
y1 = df2["medv"]

In [94]:
x1_train ,x1_test,y1_train,y1_test =train_test_split(x1,y1,test_size=0.25,random_state=10)

In [95]:
from sklearn.neighbors import KNeighborsRegressor

In [96]:
regressor  = KNeighborsRegressor(n_neighbors=5,algorithm='auto')

In [100]:
regressor.fit(x1_train,y1_train)

KNeighborsRegressor()

In [101]:
y1_pred = regressor.predict(x1_test)

In [102]:
from sklearn.metrics import r2_score

In [103]:
print(r2_score(y1_test,y1_pred))

0.6719910382472389


In [109]:
# ANS 3:
parametrs = {
    'n_neighbors':[1,2,3,4,5,6,7,8,9],
    'algorithm':['ball_tree','kd_tree']
}

In [110]:
from sklearn.model_selection import GridSearchCV

In [111]:
clf = GridSearchCV(classifier,param_grid=parametrs,cv=3,verbose=3,refit=True)

In [112]:
clf.fit(x_train,y_train)

Fitting 3 folds for each of 18 candidates, totalling 54 fits
[CV 1/3] END algorithm=ball_tree, n_neighbors=1;, score=0.868 total time=   0.0s
[CV 2/3] END algorithm=ball_tree, n_neighbors=1;, score=0.919 total time=   0.0s
[CV 3/3] END algorithm=ball_tree, n_neighbors=1;, score=1.000 total time=   0.0s
[CV 1/3] END algorithm=ball_tree, n_neighbors=2;, score=0.921 total time=   0.0s
[CV 2/3] END algorithm=ball_tree, n_neighbors=2;, score=0.838 total time=   0.0s
[CV 3/3] END algorithm=ball_tree, n_neighbors=2;, score=0.973 total time=   0.0s
[CV 1/3] END algorithm=ball_tree, n_neighbors=3;, score=0.895 total time=   0.0s
[CV 2/3] END algorithm=ball_tree, n_neighbors=3;, score=0.919 total time=   0.0s
[CV 3/3] END algorithm=ball_tree, n_neighbors=3;, score=0.973 total time=   0.0s
[CV 1/3] END algorithm=ball_tree, n_neighbors=4;, score=0.921 total time=   0.0s
[CV 2/3] END algorithm=ball_tree, n_neighbors=4;, score=0.892 total time=   0.0s
[CV 3/3] END algorithm=ball_tree, n_neighbors=4;

GridSearchCV(cv=3, estimator=KNeighborsClassifier(n_neighbors=3),
             param_grid={'algorithm': ['ball_tree', 'kd_tree'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9]},
             verbose=3)

In [113]:
clf.best_params_

{'algorithm': 'ball_tree', 'n_neighbors': 1}

In [114]:
# ANS 4:
from sklearn.preprocessing import StandardScaler

In [115]:
scaler = StandardScaler()

In [123]:
scaler.fit_transform(x1_train)

array([[-0.23129049, -0.48214334,  1.15722245, ..., -1.31262649,
        -0.12068074,  0.21148003],
       [-0.38232604, -0.48214334, -0.2326932 , ...,  0.43624006,
        -0.37121508,  0.13215633],
       [-0.418341  , -0.48214334, -1.23923336, ...,  0.45387482,
        -0.95814105,  1.27668401],
       ...,
       [-0.16882547, -0.48214334,  0.94471469, ...,  0.18079703,
         0.04821882, -0.15114259],
       [-0.40749396, -0.48214334,  2.02879146, ...,  0.32990981,
         0.25512078, -0.06048694],
       [-0.34348321,  0.34940308, -1.08416012, ...,  0.40691838,
        -0.35854762,  0.09816046]])

In [124]:
scaler.transform(x1_test)

array([[-0.41983271,  0.88990826, -1.34117965, ...,  0.41693575,
        -0.57248706,  0.73275006],
       [-0.42338863,  2.01249593, -1.2334899 , ...,  0.4170401 ,
        -1.12141062,  1.03871291],
       [-0.42187963,  2.84404235, -1.17031192, ...,  0.45387482,
        -1.17208049,  0.17748416],
       ...,
       [-0.35317339, -0.48214334, -0.48540514, ...,  0.24497083,
         0.25512078, -0.60442088],
       [-0.41583717, -0.48214334, -1.07267322, ...,  0.43926615,
        -0.5570046 ,  0.18881612],
       [ 0.37002059, -0.48214334,  0.94471469, ..., -2.67832848,
         1.19955081, -1.23901048]])

In [125]:
# ANS 5:
classifier1  = KNeighborsClassifier(n_neighbors=3,weights='distance')

In [126]:
classifier1.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3, weights='distance')

In [127]:
y_pred2 = classifier.predict(x_test)

In [128]:
print(accuracy_score(y_test,y_pred2))

0.9736842105263158


In [131]:
# ANS 6:
scaler.fit_transform(x_train)

array([[ 2.2256217 , -1.08471126,  1.7819506 ,  1.44375315],
       [ 1.26827314,  0.04645877,  0.77482629,  1.44375315],
       [-1.00542968,  0.72516079, -1.18347098, -1.02396308],
       [-1.00542968,  0.95139479, -1.18347098, -0.76420347],
       [-0.76609254, -0.85847725,  0.10341009,  0.27483494],
       [-1.60377252, -1.76341327, -1.35132503, -1.15384288],
       [ 0.55026173,  0.49892678,  0.55102089,  0.53459454],
       [-0.76609254,  2.30879882, -1.23942233, -1.41360248],
       [ 1.26827314,  0.04645877,  0.66292359,  0.40471474],
       [ 0.07158745,  0.27269277,  0.60697224,  0.79435414],
       [-0.28741826, -0.63224325,  0.66292359,  1.05411374],
       [ 1.028936  ,  0.49892678,  1.11053439,  1.70351275],
       [ 0.43059316, -1.98964728,  0.43911819,  0.40471474],
       [ 1.62727885,  1.1776288 ,  1.3343398 ,  1.70351275],
       [-0.40708683, -1.53717927, -0.00849262, -0.24468427],
       [ 0.19125602, -0.40600924,  0.43911819,  0.40471474],
       [ 0.6699303 ,  0.

In [130]:
scaler.transform(x_test)

array([[ 0.55026173, -1.76341327,  0.38316684,  0.14495514],
       [ 0.6699303 , -0.85847725,  0.88672899,  0.92423394],
       [-0.5267554 ,  1.4038628 , -1.23942233, -1.28372268],
       [ 0.31092459, -0.17977524,  0.49506954,  0.27483494],
       [-1.00542968,  0.49892678, -1.29537368, -1.28372268],
       [-1.00542968, -2.44211529, -0.12039532, -0.24468427],
       [ 0.55026173, -1.31094526,  0.66292359,  0.40471474],
       [-0.04808112, -0.85847725,  0.21531279, -0.24468427],
       [-0.88576111,  0.72516079, -1.23942233, -1.28372268],
       [-0.16774969, -0.63224325,  0.43911819,  0.14495514],
       [-0.28741826, -0.17977524,  0.43911819,  0.40471474],
       [-0.04808112, -0.85847725,  0.77482629,  0.92423394],
       [-0.40708683, -1.76341327,  0.15936144,  0.14495514],
       [-1.12509825, -0.17977524, -1.29537368, -1.28372268],
       [-0.88576111,  1.63009681, -1.23942233, -1.15384288],
       [ 1.14860457, -0.17977524,  0.99863169,  1.18399355],
       [ 0.19125602,  0.

In [137]:
# ANS 7:
# EUCLEDIAN DISTANCE
p1 = np.array([1,2])
p2 = np.array([3,4])
distance = np.sqrt(np.sum((p1 - p2)**2))

In [138]:
distance

2.8284271247461903

In [142]:
# ANS 8:
# MANHATTAN DISTANCE
d1 = np.sum(p2 - p1)
d1

4